"""add website crawler models

Revision ID: e76552c4d7e9
Revises: 9703d120771f
Create Date: 2025-07-14 22:29:50.413755

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e76552c4d7e9'
down_revision = '9703d120771f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urlanalysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawled_url_id', sa.Integer(), nullable=False),
    sa.Column('html_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=False),
    sa.Column('h2_count', sa.Integer(), nullable=False),
    sa.Column('h3_count', sa.Integer(), nullable=False),
    sa.Column('h4_count', sa.Integer(), nullable=False),
    sa.Column('h5_count', sa.Integer(), nullable=False),
    sa.Column('h6_count', sa.Integer(), nullable=False),
    sa.Column('internal_links_count', sa.Integer(), nullable=False),
    sa.Column('external_links_count', sa.Integer(), nullable=False),
    sa.Column('inaccessible_links_count', sa.Integer(), nullable=False),
    sa.Column('has_login_form', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['crawled_url_id'], ['crawledurl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brokenlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['urlanalysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brokenlink')
    op.drop_table('urlanalysis')
    # ### end Alembic commands ###
